services:
  redis-test:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
  mongo-test:
    image: mongo:6.0
    env_file: .env.test
    ports:
      - "${MONGODB_PORT}:27017"
    command: mongod --noauth
    healthcheck: 
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 1s
      timeout: 3s
      retries: 5
  cassandra-test:
    image: cassandra:4.1
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-test
      - CASSANDRA_START_RPC=false
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M
      - CASSANDRA_ENABLE_USER_DEFINED_FUNCTIONS=true
    ports:
      - "${CASSANDRA_PORT}:${CASSANDRA_PORT}"
    volumes:
      - cassandra_data_test:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -u cassandra -p cassandra cassandra-test 9042 -e 'DESCRIBE KEYSPACES' && exit 0 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10
    container_name: cassandra-test

volumes:
  cassandra_data_test: