services:
  redis-test:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
  mongo-test:
    image: mongo:6.0
    env_file: .env.test
    ports:
      - "${MONGODB_PORT}:27017"
    command: mongod --noauth
    healthcheck: 
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 1s
      timeout: 3s
      retries: 5