name: EventHub (Reusable)

on:
  workflow_call:
    inputs:
      lab:
        description: 'Lab number'
        required: true
        type: string

jobs:
  lab1:
    name: Lab 1
    if: ${{ inputs.lab >= 1 }}
    uses: ./.github/workflows/reusable_eventhub_lab1.yml
    with:
      scripts_dir: '.github/scripts'
      lab_check_dir: 'autograder/cmd/lab1'
  lab2:
    name: Lab 2
    needs: lab1
    if: ${{ inputs.lab >= 2 }}
    uses: ./.github/workflows/reusable_eventhub_lab2.yml
    with:
      scripts_dir: '.github/scripts'
      lab_check_dir: 'autograder/cmd/lab2'
  lab3:
    name: Lab 3
    needs: lab2
    if: ${{ inputs.lab >= 3 }}
    uses: ./.github/workflows/reusable_eventhub_lab3.yml
    with:
      scripts_dir: '.github/scripts'
      lab_check_dir: 'autograder/cmd/lab3'
